
  server:
    port: 8082
  weichat:
    mini:
      appId: wx7989adf212f693c5
      secret: 3b88e399823b29ba453a81ff1f074225
      api:
        host: https://api.weixin.qq.com/sns/jscode2session
  spring:
    application:
      name: oauth-server   # 应用名称

    jpa:
      open-in-view: true
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: create
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

    # 数据源 配置
    datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3306/udriving?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver

#    # redis 配置
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password:
#      database: 0
#      jedis:
#        pool:
#          #最大连接数
#          max-active: 8
#          #最大空闲
#          max-idle: 8
#          #最大阻塞等待时间(负数表示没限制)
#          max-wait: -1ms
#          #最小空闲
#          min-idle: 0
#      #连接超时时间
#      timeout: 1000ms



  # JWT 配置
  jwt:
    # 存放Token的Header Key
    header: Authorization
    # 密匙key
    secret: mySecret
    # 过期时间   单位秒 7天后过期  604800
    expiration: 3600
    # 自定义token 前缀字符
    tokenHead: Bearer-
    # 超时时间   单位秒
    access_token: 3600
    # 刷新token时间   单位秒
    refresh_token: 3600
    route:
      authentication:
        path: login/entry
        refresh: oauth/refresh
        register: login/account


  # 配置不需要认证的接口
  com:
    example:
      oauth:
        security:
          antMatchers:
            /auth/v1/api/login/**,
            /auth/v1/api/module/tree/**,
            /auth/v1/api/grid/**


  # 日志
  logging:
    level:
      org:
        springframework:
          security: DEBUG
